service: discord-faceit-bot

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  webhooks:
    handler: bin/webhook
    events:
      - httpApi:
          path: /faceit-webhooks
          method: post